### ISSUE TITLE
bash support / bash alternative install

### ISSUE THREAD

**Issue by MichaelDimmitt** [MenkeTechnologies/zsh-learn#2]
## I want to use this; but I want to use bash.

<img width="1350" alt="Screenshot 2024-06-10 at 8 46 18 AM" src="https://github.com/MenkeTechnologies/zsh-learn/assets/11463275/bc08bb7e-91c0-44b1-aaca-ca95b29823c9">

**Comment by MenkeTechnologies** [comment]
there are too many zsh specific features to support in bash.
